FROM python:3.10.7-slim as python-base
ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100
ENV PATH="/root/.local/bin:$PATH"

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y gcc libc-dev make git libffi-dev python3-dev libxml2-dev libxslt-dev
RUN apt-get install -y default-libmysqlclient-dev pkg-config
RUN apt-get install -y libpq-dev

FROM python-base as poetry
RUN apt-get install --no-install-recommends -y \
        # deps for installing poetry
        curl \
        # deps for building python deps
        build-essential

# install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN poetry --version
RUN poetry config virtualenvs.create false


# cleanup
RUN rm -rf /var/lib/apt/lists/

COPY . ./
RUN poetry install

FROM poetry as runtime
WORKDIR /app
COPY ./dev.harambot.db /app/dev.harambot.db
CMD ["harambot_reports"]
